In [25]:
import pandas as pd 
import dask.dataframe as dd

#Declare file locations
root = "/Users/npatel/Desktop/Dr.Chen_Lab/Neel_Data_Results/Task1-Eagle_Data"
#import data from files as dataframe
EAGLE_aggression_Public_2 = pd.read_csv("/Users/npatel/Desktop/Dr.Chen_Lab/Data/EAGLE_aggression_Public_2", sep = '\s+' )
chrom_data = pd.read_csv("/Users/npatel/Desktop/Dr.Chen_Lab/Genome_Data/ALL-snps_hg18.txt", sep='\s+')
missing = pd.read_csv("/Users/npatel/Desktop/Dr.Chen_Lab/Data/EAGLE_aggression_Public_2_FOUND.csv")
chrom_data = chrom_data.astype({"chromEnd": int})

missingChrom = chrom_data
EAGLE_aggression_Public_2

,SNP,A1,A2,BETA,P,Direction,HetISq,HetChiSq,HetDf,HetPVal,SAMPLESIZE,ImpQuality
0,rs2326918,a,g,0.580,0.5618,--+--+--+,0.0,7.150,8,0.5205,18834,8.26766
1,rs10760160,a,c,1.144,0.2524,++-++-+++,0.0,6.360,8,0.6070,18833,8.90308
2,rs977590,a,g,1.107,0.2682,++++++-++,0.0,3.013,8,0.9335,18834,8.17451
3,rs17278013,t,g,-0.490,0.6239,--++---++,0.0,2.809,8,0.9457,18834,8.70657
4,rs7852050,a,g,1.228,0.2193,-+-++++++,0.0,6.392,8,0.6034,18833,8.16806
...,...,...,...,...,...,...,...,...,...,...,...,...
2188523,rs6771006,t,c,1.420,0.1556,+--++++??,0.0,4.641,6,0.5907,16119,6.24803
2188524,rs13206561,a,g,-0.229,0.8192,-+---++-+,0.0,5.453,8,0.7083,18833,8.49673
2188525,rs3809887,a,g,-0.555,0.5789,-+-+----+,4.9,8.415,8,0.3940,18833,8.98656
2188526,rs16862136,c,g,-0.357,0.7209,--++--+-+,0.0,7.229,8,0.5122,18834,8.33865
2188527,rs2373166,t,c,0.828,0.4075,--+-+++++,39.6,13.241,8,0.1038,18834,8.90777

In [26]:
#compare chrom data to Eagle data by RS#
merge2 = pd.merge(EAGLE_aggression_Public_2, chrom_data, on = "SNP",  how='outer', indicator=True)

# RSname only in Eagle data
Eagle_without_chrom = merge2.loc[merge2["_merge"] == "left_only"].drop("_merge", axis=1)
Eagle_without_chrom = Eagle_without_chrom.drop('#chrom',axis =1)
Eagle_without_chrom = Eagle_without_chrom.drop('chromEnd',axis =1)

missing_merge  = pd.merge(Eagle_without_chrom, missing, on = "SNP", how = 'outer', indicator=True)

Eagle_without_chrom.rename(columns={'#chrom':'CHR', 'chromEnd':'BP'}, inplace=True)

Eagle_without_chrom.to_csv(root + '/' + "EAGLE_aggression_Public_2_(no matching chrom).csv",index = False)
missing = missing_merge.loc[missing_merge["_merge"] == "both"].drop("_merge", axis=1)
missing.rename(columns={'#chrom':'CHR', 'chromEnd':'BP'}, inplace=True)
missing_merge

,SNP,A1,A2,BETA,P,Direction,HetISq,HetChiSq,HetDf,HetPVal,SAMPLESIZE,ImpQuality,#chrom,chromEnd,_merge
0,rs12182264,t,c,-0.027,0.97880,+++----+-,36.2,12.546,8.0,0.1284,18834.0,8.51339,chr6,167109951,both
1,rs4131818,t,c,0.087,0.93040,++-+---++,22.1,10.274,8.0,0.2463,18834.0,8.92973,chr5,41880172,both
2,rs11153570,a,t,1.082,0.27920,+++-+---+,36.7,12.636,8.0,0.1250,18834.0,8.97619,chr6,115924472,both
3,rs10735697,a,g,0.781,0.43480,++-+++-+-,0.0,2.725,8.0,0.9504,18828.0,7.67952,chr13,23584077,both
4,rs4348205,t,c,-0.794,0.42740,+--+--++-,37.7,12.837,8.0,0.1176,18834.0,8.90749,chr5,113888946,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,rs10755615,t,g,0.887,0.37510,-++-+++-+,0.0,4.705,8.0,0.7886,18831.0,7.99703,chr6,21714658,both
1762,rs10945958,a,c,0.664,0.50690,--+++---+,0.0,7.344,8.0,0.5000,18831.0,8.01443,chr6,164456745,both
1763,rs3736633,a,g,0.427,0.66950,--+-++-++,31.7,11.713,8.0,0.1645,18834.0,8.41214,chr2,227662843,both
1764,rs2662733,t,g,-2.009,0.04453,+-------+,0.0,4.481,8.0,0.8113,18834.0,8.91527,chr4,121379679,both
1765,rs3858895,a,g,0.176,0.86020,++-+--++-,0.0,3.118,8.0,0.9267,18831.0,7.42792,chr15,59792702,both

In [27]:
#compare chrom data to Eagle data by RS#
merge3 = pd.merge(EAGLE_aggression_Public_2, chrom_data, on = "SNP",  how='outer', indicator=True)

# RSname only in Chrom data 
Chrom_only = merge3.loc[merge3["_merge"] == "right_only"].drop("_merge", axis=1)
Chrom_only.rename(columns={'SNP':'rsName', '#chrom':'CHR', 'chromEnd':'BP'}, inplace=True)
Chrom_only_temp = Chrom_only[["rsName", "CHR", "BP"]]
Chrom_only_temp = Chrom_only_temp.astype({"BP": int})
#Chrom_only_temp = Chrom_only_temp[["CHR", "BP", "SNP", "A1", "A2", "BETA", "P", "Direction", "HetISq", "HetChiSq", "HetDf", "HetPVal", "SAMPLESIZE", "ImpQuality"]]
Chrom_only_temp['CHR'] = Chrom_only_temp['CHR'].str.replace("chr","")
Chrom_only_temp.to_csv(root + '/' + "ALL-snps_hg18(no matching RS# in EAGLE).csv", index = False)

Chrom_only_temp

              rsName         CHR         BP
2205992   rs72059099           1   16781350
2205993   rs71260122           1   16788198
2205994   rs71260122           1  144013960
2205995   rs72496645           1   16782082
2205996   rs71808286           1  100667832
...              ...         ...        ...
18835292  rs71413563  6_qbl_hap2    4213740
18835293  rs71062804  6_qbl_hap2    4213868
18835294  rs74223659  6_qbl_hap2    4278322
18835295  rs74200144  6_qbl_hap2    4306208
18835296  rs74223645  6_qbl_hap2    4462138

[16629305 rows x 3 columns]

In [28]:
#compare chrom data to Eagle data by RS#
merge4 = pd.merge(EAGLE_aggression_Public_2, chrom_data, on = "SNP",  how='outer', indicator=True)

# RSname in both data sets
both = merge4.loc[merge4["_merge"] == "both"].drop("_merge", axis=1)
both.rename(columns={'#chrom':'CHR', 'chromEnd':'BP'}, inplace=True)
both = both.astype({"BP": int})
both = both[["CHR", "BP", "SNP", "A1", "A2", "BETA", "P", "Direction", "HetISq", "HetChiSq", "HetDf", "HetPVal", "SAMPLESIZE", "ImpQuality"]]
both['CHR'] = both["CHR"].str.replace("chr","")
both.to_csv(root + '/' + "EAGLE_aggression_Public_2 (matched chrom data).csv",index = False)

both

,CHR,BP,SNP,A1,A2,BETA,P,Direction,HetISq,HetChiSq,HetDf,HetPVal,SAMPLESIZE,ImpQuality
0,6,130881784,rs2326918,a,g,0.580,0.5618,--+--+--+,0.0,7.150,8.0,0.5205,18834.0,8.26766
1,9,123043147,rs10760160,a,c,1.144,0.2524,++-++-+++,0.0,6.360,8.0,0.6070,18833.0,8.90308
2,7,34415290,rs977590,a,g,1.107,0.2682,++++++-++,0.0,3.013,8.0,0.9335,18834.0,8.17451
3,14,24783304,rs17278013,t,g,-0.490,0.6239,--++---++,0.0,2.809,8.0,0.9457,18834.0,8.70657
4,9,9151167,rs7852050,a,g,1.228,0.2193,-+-++++++,0.0,6.392,8.0,0.6034,18833.0,8.16806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2205987,3,1981604,rs6771006,t,c,1.420,0.1556,+--++++??,0.0,4.641,6.0,0.5907,16119.0,6.24803
2205988,6,85991161,rs13206561,a,g,-0.229,0.8192,-+---++-+,0.0,5.453,8.0,0.7083,18833.0,8.49673
2205989,17,36878052,rs3809887,a,g,-0.555,0.5789,-+-+----+,4.9,8.415,8.0,0.3940,18833.0,8.98656
2205990,2,221648486,rs16862136,c,g,-0.357,0.7209,--++--+-+,0.0,7.229,8.0,0.5122,18834.0,8.33865
2205991,14,85805887,rs2373166,t,c,0.828,0.4075,--+-+++++,39.6,13.241,8.0,0.1038,18834.0,8.90777

In [37]:
final = both.append(missing, ignore_index = True)
final = final[["CHR", "BP", "SNP", "A1", "A2", "BETA", "P", "Direction", "HetISq", "HetChiSq", "HetDf", "HetPVal", "SAMPLESIZE", "ImpQuality"]]
final['CHR'] = final['CHR'].str.replace("chr","")
final = final.sort_values(by = ['CHR'])
final.to_csv(root + '/' + "EAGLE_aggression_Public_2_FINAL_MERGED.txt", sep = '\t', index = False)

duplicates = final[final.duplicated(['SNP'], keep=False)]
duplicates = duplicates[["CHR", "BP", "SNP", "A1", "A2", "BETA", "P", "Direction", "HetISq", "HetChiSq", "HetDf", "HetPVal", "SAMPLESIZE", "ImpQuality"]]
duplicates["CHR"] = duplicates["CHR"].str.replace("chr","")
duplicates = duplicates.sort_values(by = ['CHR'])
duplicates.to_csv(root + '/' + "EAGLE_aggression_Public_2 duplicates.txt", sep = '\t', index = False)

without_duplicates = final.drop_duplicates(subset=['SNP'], keep = 'first')
without_duplicates = without_duplicates[["CHR", "BP", "SNP", "A1", "A2", "BETA", "P", "Direction", "HetISq", "HetChiSq", "HetDf", "HetPVal", "SAMPLESIZE", "ImpQuality"]]
without_duplicates["CHR"] = without_duplicates["CHR"].str.replace("chr","")
without_duplicates["CHR"] = without_duplicates["CHR"].astype(object)
without_duplicates = without_duplicates.sort_values(by = ['CHR'])
without_duplicates.to_csv( root + '/' + "EAGLE_aggression_Public_2_FINAL_MERGED(without Duplicates).txt", sep = '\t', index = False)
without_duplicates

,CHR,BP,SNP,A1,A2,BETA,P,Direction,HetISq,HetChiSq,HetDf,HetPVal,SAMPLESIZE,ImpQuality
349859,1,5875932,rs11122104,t,c,1.392,0.16400,++++-++++,0.0,6.394,8.0,0.60320,18834.0,8.96418
2083617,1,94309883,rs12758774,t,c,1.642,0.10060,+-+++++++,0.0,2.810,8.0,0.94570,18833.0,8.46527
1330085,1,207960666,rs6672256,a,t,0.167,0.86780,--++-+--+,0.0,7.526,8.0,0.48100,18834.0,8.58994
1098239,1,233039175,rs822841,a,g,-0.697,0.48610,-++----+-,0.0,6.804,8.0,0.55800,18834.0,8.80574
1330083,1,212439580,rs1223766,t,c,-1.830,0.06719,+-+-----?,38.9,11.458,7.0,0.11990,17399.0,7.84824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128559,9,16345783,rs6475043,t,c,0.844,0.39860,-++++-+-+,0.0,4.393,8.0,0.82010,18832.0,7.63996
799389,9,87923572,rs11793816,a,g,0.257,0.79730,++-++--++,0.0,4.716,8.0,0.78740,18831.0,8.25523
1128496,9,128206538,rs7847688,t,c,0.647,0.51790,+++---+-+,20.6,10.078,8.0,0.25960,18834.0,8.87648
1879275,9,1973216,rs10964264,t,c,-0.487,0.62610,-+---+-++,42.4,13.894,8.0,0.08456,18834.0,7.66036
2059498,9,78341685,rs10781366,a,g,-1.056,0.29090,--------+,0.0,4.301,8.0,0.82900,18830.0,7.50036

In [34]:
both

,CHR,BP,SNP,A1,A2,BETA,P,Direction,HetISq,HetChiSq,HetDf,HetPVal,SAMPLESIZE,ImpQuality
0,6,130881784,rs2326918,a,g,0.580,0.5618,--+--+--+,0.0,7.150,8.0,0.5205,18834.0,8.26766
1,9,123043147,rs10760160,a,c,1.144,0.2524,++-++-+++,0.0,6.360,8.0,0.6070,18833.0,8.90308
2,7,34415290,rs977590,a,g,1.107,0.2682,++++++-++,0.0,3.013,8.0,0.9335,18834.0,8.17451
3,14,24783304,rs17278013,t,g,-0.490,0.6239,--++---++,0.0,2.809,8.0,0.9457,18834.0,8.70657
4,9,9151167,rs7852050,a,g,1.228,0.2193,-+-++++++,0.0,6.392,8.0,0.6034,18833.0,8.16806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2205987,3,1981604,rs6771006,t,c,1.420,0.1556,+--++++??,0.0,4.641,6.0,0.5907,16119.0,6.24803
2205988,6,85991161,rs13206561,a,g,-0.229,0.8192,-+---++-+,0.0,5.453,8.0,0.7083,18833.0,8.49673
2205989,17,36878052,rs3809887,a,g,-0.555,0.5789,-+-+----+,4.9,8.415,8.0,0.3940,18833.0,8.98656
2205990,2,221648486,rs16862136,c,g,-0.357,0.7209,--++--+-+,0.0,7.229,8.0,0.5122,18834.0,8.33865
2205991,14,85805887,rs2373166,t,c,0.828,0.4075,--+-+++++,39.6,13.241,8.0,0.1038,18834.0,8.90777